// @ts-check

export function createElements() {
  return {
    backendChip: document.querySelector("#backend-chip"),
    captureChip: document.querySelector("#capture-chip"),
    cloudChip: document.querySelector("#cloud-chip"),
    sttChip: document.querySelector("#stt-chip"),
    backendNote: document.querySelector("#backend-note"),
    transcriptHint: document.querySelector("#transcript-hint"),
    transcriptReturnLive: document.querySelector("#transcript-return-live"),
    questionBanner: document.querySelector("#question-banner"),
    partialBox: document.querySelector("#partial-box"),
    segmentList: document.querySelector("#segment-list"),
    manualAssistantCard: document.querySelector("#manual-assistant-card"),
    automaticAssistantCard: document.querySelector("#automatic-assistant-card"),
    actionAnswerButton: document.querySelector("#action-answer-button"),
    actionSummaryButton: document.querySelector("#action-summary-button"),
    actionCommentButton: document.querySelector("#action-comment-button"),
    clearSelectionButton: document.querySelector("#clear-selection-button"),
    clearAllButton: document.querySelector("#clear-all-button"),
    selectionStatus: document.querySelector("#selection-status"),
    appVersion: document.querySelector("#app-version"),
    themeToggle: document.querySelector("#theme-toggle"),
    errorList: document.querySelector("#error-list"),
    settingsMode: document.querySelector("#settings-mode"),
    openaiModel: document.querySelector("#openai-model"),
    retentionDays: document.querySelector("#retention-days"),
    transcriptStorage: document.querySelector("#transcript-storage"),
    autoStartCloud: document.querySelector("#auto-start-cloud"),
    assistantInstruction: document.querySelector("#assistant-instruction"),
    saveSettings: document.querySelector("#save-settings"),
    saveAgentConfig: document.querySelector("#save-agent-config"),
    purgeHistory: document.querySelector("#purge-history"),
    primingFileInput: document.querySelector("#priming-file-input"),
    uploadPrimingDocuments: document.querySelector("#upload-priming-documents"),
    primingDocumentList: document.querySelector("#priming-document-list"),
    settingsNote: document.querySelector("#settings-note"),
    currentSink: document.querySelector("#current-sink"),
    monitorSource: document.querySelector("#monitor-source"),
    sttStatus: document.querySelector("#stt-status"),
    sessionId: document.querySelector("#session-id"),
    privacyPause: document.querySelector("#privacy-pause"),
    cloudPause: document.querySelector("#cloud-pause"),
    cloudAutoPause: document.querySelector("#cloud-auto-pause"),
    audioUploadActive: document.querySelector("#audio-upload-active"),
    privacyCapture: document.querySelector("#privacy-capture"),
    privacyCloud: document.querySelector("#privacy-cloud"),
    privacyStorage: document.querySelector("#privacy-storage"),
    privacyBackend: document.querySelector("#privacy-backend"),
    sessionList: document.querySelector("#session-list"),
    sessionDetail: document.querySelector("#session-detail"),
  };
}

